tasks:
  - task: tasks.clean_core_dump.CleanCoreDumpTask
    executor: ThreadPoolExecutor
    task_store: default
    trigger_type: interval
    interval: 5
  - task: tasks.task1.Task1
    executor: ProcessPoolExecutor
    task_store: default
    trigger_type: interval
    interval: 2
    subscribers:
      - tasks.task1.Subscriber1
      - tasks.task1.Subscriber2
  - task: tasks.task2.Task2
    executor: ThreadPoolExecutor
    task_store: default
    trigger_type: cron
    cron:
      expression: "*/5 * * * * *"
      timezone: "Asia/Shanghai"
    subscribers:
      - tasks.task2.Subscriber1
      - tasks.task2.Subscriber2